# Generated by Django 3.1.5 on 2021-01-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organizer_webinars',
            field=models.ManyToManyField(blank=True, related_name='organizers', to='webinar.Webinar'),
        ),
    ]
