# Generated by Django 3.1.5 on 2021-01-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
        ('person', '0002_person_organizer_webinars'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='participant_webinars',
            field=models.ManyToManyField(blank=True, related_name='participants', to='webinar.Webinar'),
        ),
    ]
