# Generated by Django 3.1.6 on 2021-02-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_participant_webinars'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slugName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
