# Generated by Django 3.1.6 on 2021-02-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20210213_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='participant_webinars',
        ),
    ]
