# Generated by Django 3.1.6 on 2021-02-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_hosts',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='host.Host'),
        ),
    ]
