# Generated by Django 3.1.6 on 2021-02-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slugName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
