# Generated by Django 3.1.6 on 2021-02-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_slugname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='orgName',
        ),
        migrations.AddField(
            model_name='organization',
            name='orgNameCn',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='orgNameShort',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='orgNameShortCn',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
