# Generated by Django 3.1.6 on 2021-02-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20210215_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='orgName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='orgNameCn',
            new_name='nameCn',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='orgNameShort',
            new_name='nameShort',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='orgNameShortCn',
            new_name='nameShortCn',
        ),
    ]
