# Generated by Django 3.1.6 on 2021-02-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20210215_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_hosts',
        ),
    ]
