# Generated by Django 3.1.6 on 2021-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0012_remove_webinar_hostorganization'),
        ('organization', '0008_remove_organization_organization_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hostedWebinars',
            field=models.ManyToManyField(blank=True, related_name='hostOrganizations', to='webinar.Webinar'),
        ),
    ]
