# Generated by Django 3.1.6 on 2021-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_submission'),
        ('organization', '0009_organization_hostedwebinars'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hostedLeads',
            field=models.ManyToManyField(blank=True, related_name='hostOrganizations', to='lead.Lead'),
        ),
    ]
