# Generated by Django 3.1.7 on 2021-03-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organization_hostedsources'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='urlPatterns',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
