# Generated by Django 3.1.5 on 2021-01-18 19:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=100)),
                ('tagType', models.CharField(choices=[('LANGUAGE', 'Language'), ('SUBJECT', 'Subject')], default='SUBJECT', max_length=255)),
                ('TagSubject', models.CharField(choices=[('PHILOSOPHY', 'Philosophy'), ('LITERATURE', 'Literature'), ('ART', 'Art'), ('POLITICS', 'Politics'), ('ECONOMICS', 'Economics'), ('LAW', 'Law'), ('SOCIOLOGY', 'Sociology'), ('ANTHROPOLOGY', 'Anthropology')], default='PHILOSOPHY', max_length=255)),
            ],
        ),
    ]
