# Generated by Django 3.1.5 on 2021-01-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_auto_20210123_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagNameCn',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
