# Generated by Django 3.1.5 on 2021-01-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0005_tag_tagnamecn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagType',
            field=models.CharField(choices=[('LANGUAGE', 'Language'), ('DISCIPLINE', 'Discipline'), ('TOPIC', 'Topic')], default='DISCIPLINE', max_length=255),
        ),
    ]
