# Generated by Django 3.1.5 on 2021-01-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0006_auto_20210124_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tagNameCn',
        ),
    ]
