# Generated by Django 3.1.6 on 2021-02-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0008_auto_20210131_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagNameCn',
            field=models.CharField(default='', max_length=100),
        ),
    ]
