# Generated by Django 3.1.6 on 2021-02-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0009_tag_tagnamecn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slugName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
