# Generated by Django 3.1.6 on 2021-02-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0010_tag_slugname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slugName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
