# Generated by Django 3.1.6 on 2021-02-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0011_auto_20210204_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagNameCn',
            new_name='nameCn',
        ),
    ]
