# Generated by Django 3.1.6 on 2021-02-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_submission'),
        ('tag', '0012_auto_20210215_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='tags', to='lead.Lead'),
        ),
    ]
