# Generated by Django 3.1.6 on 2021-02-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('tag', '0013_tag_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='tags', to='sources.Source'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagType',
            field=models.CharField(choices=[('LANGUAGE', 'Language'), ('DISCIPLINE', 'Discipline'), ('TOPIC', 'Topic'), ('AREA', 'Area')], default='TOPIC', max_length=255),
        ),
    ]
