# Generated by Django 3.1.7 on 2021-02-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggingrecord', '0001_initial'),
        ('tag', '0014_auto_20210220_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='taggingrecords',
            field=models.ManyToManyField(blank=True, related_name='tags', to='taggingrecord.TaggingRecord'),
        ),
    ]
