# Generated by Django 3.1.7 on 2021-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0017_auto_20210228_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagType',
            field=models.CharField(choices=[('LANGUAGE', 'Language'), ('DOMAIN', 'Domain'), ('DISCIPLINE', 'Discipline'), ('SUBFIELD', 'Subfield'), ('TOPIC', 'Topic'), ('AREA', 'Area')], default='TOPIC', max_length=255),
        ),
    ]
