# Generated by Django 3.1.5 on 2021-01-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210118_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=100),
        ),
    ]
