# Generated by Django 3.1.6 on 2021-02-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='display_name',
            new_name='displayName',
        ),
    ]
