# Generated by Django 3.1.6 on 2021-02-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_userprofile_savedwebinars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='Europe/London', max_length=100),
        ),
    ]
