# Generated by Django 3.1.6 on 2021-02-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20210216_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isTagger',
            field=models.BooleanField(default=False, verbose_name='tagger status'),
        ),
    ]
