# Generated by Django 3.1.7 on 2021-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20210224_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isDirectPoster',
            field=models.BooleanField(default=False, verbose_name='Direct Poster'),
        ),
    ]
