# Generated by Django 3.1.7 on 2021-02-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_userprofile_isdirectposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isLeadCollector',
            field=models.BooleanField(default=False, verbose_name='Lead Poster'),
        ),
    ]
