# Generated by Django 3.1.7 on 2021-02-22 21:47

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinar', '0018_auto_20210222_2131'),
        ('userprofile', '0008_userprofile_istagger'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggingRecord',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taggingRecords', to='userprofile.userprofile')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggingRecords', to='webinar.webinar')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
