# Generated by Django 3.1.5 on 2021-01-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('profilefilter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefilter',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='userprofile.userprofile'),
        ),
    ]
