# Generated by Django 3.1.6 on 2021-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_host_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='slugName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
