# Generated by Django 3.1.6 on 2021-02-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_host_slugname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='name',
            new_name='hostName',
        ),
        migrations.AddField(
            model_name='host',
            name='hostNameCn',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='hostNameShort',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='hostNameShortCn',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
