# Generated by Django 3.1.6 on 2021-02-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_auto_20210215_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='hostName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='hostNameCn',
            new_name='nameCn',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='hostNameShort',
            new_name='nameShort',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='hostNameShortCn',
            new_name='nameShortCn',
        ),
    ]
