# Generated by Django 3.1.6 on 2021-02-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('host', '0008_host_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_sources',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='sources.Source'),
        ),
    ]
