# Generated by Django 3.1.7 on 2021-03-04 02:25

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinar', '0026_webinar_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterRecord',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tweetId', models.CharField(blank=True, max_length=255)),
                ('inReplyToTargetId', models.CharField(blank=True, max_length=255, null=True)),
                ('webinar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitterRecords', to='webinar.webinar')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
