# Generated by Django 3.1.5 on 2021-01-18 19:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('targetId', models.UUIDField(blank=True)),
                ('targetType', models.CharField(blank=True, choices=[('WEBINAR', 'Webinar'), ('LINK', 'Link')], max_length=255)),
                ('type', models.CharField(choices=[('INCORRECT_INFO', 'Incorrect Information'), ('SUGGESTION', 'Suggestion'), ('BUG', 'Bug'), ('ADD_INFO', 'Add new information'), ('DELETE_REQUEST', 'Request deletion of an item')], max_length=255)),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
    ]
