# Generated by Django 3.1.6 on 2021-02-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0013_webinar_registrationdeadline'),
        ('speaker', '0002_speaker_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='participant_webinars',
            field=models.ManyToManyField(blank=True, related_name='participants', to='webinar.Webinar'),
        ),
    ]
