# Generated by Django 3.1.6 on 2021-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20210221_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2000, unique=True),
        ),
    ]
