# Generated by Django 3.1.5 on 2021-01-18 19:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('startDateTime', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=25535)),
            ],
        ),
    ]
