# Generated by Django 3.1.5 on 2021-02-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_auto_20210131_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('EVENT', 'EVENT'), ('BROADCAST', 'BROADCAST'), ('REGISTRATION', 'REGISTRATION'), ('DETAIL', 'DETAIL'), ('ATTACHMENT', 'ATTACHMENT'), ('CONTACT', 'CONTACT'), ('ORGANIZATION', 'ORGANIZATION'), ('RECORDING', 'RECORDING'), ('TRANSCRIPT', 'TRANSCRIPT')], max_length=100),
        ),
    ]
