# Generated by Django 3.1.7 on 2021-02-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_auto_20210201_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('EVENT', 'EVENT'), ('BROADCAST', 'BROADCAST'), ('REGISTRATION', 'REGISTRATION'), ('DETAIL', 'DETAIL'), ('ATTACHMENT', 'ATTACHMENT'), ('CONTACT', 'CONTACT'), ('ORGANIZATION', 'ORGANIZATION'), ('RECORDING', 'RECORDING'), ('TRANSCRIPT', 'TRANSCRIPT'), ('CODE', 'CODE')], max_length=100),
        ),
    ]
