export const SEARCH_DISCIPLINES: string[] = [
  'Philosophy',
  'History',
  'Anthropology',
  'Communication',
  'Economics',
  'Social Work',
  'Musicology',
  'Media Studies',
  'Sociology',
  'Area Studies',
  'Politics',
  'Classics',
  'Literature',
  'Arts',
  'Architecture',
  'Cinema',
  'Gender',
  'Law',
  'Religion',
  'Performing Arts',
  'Visual Arts',
  'Linguistics',
  'Archaeology',
  'Education',
  'human geography',
  'International Relations',
];
