# Generated by Django 3.1.5 on 2021-01-18 19:13

import uuid

import ckeditor.fields
import django.db.models.deletion
import django_extensions.db.fields
import storages.backends.s3boto3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, default='', max_length=1000)),
                ('file', models.FileField(blank=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='seminarlive-leads', querystring_auth=True), upload_to='leads')),
                ('fileOCR', ckeditor.fields.RichTextField(blank=True, max_length=65535)),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=65535)),
                ('html', ckeditor.fields.RichTextField(blank=True, max_length=655350)),
                ('json', models.JSONField(blank=True, max_length=65535, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('startDateTime', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=280)),
                ('source', models.CharField(blank=True, choices=[('EVENTBRITE', 'EVENTBRITE'), ('HNET', 'HNET')], default='', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
