# Generated by Django 3.1.5 on 2021-01-25 21:49

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='originalStartDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='originalTimeZone',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
    ]
