# Generated by Django 3.1.5 on 2021-02-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_auto_20210130_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('EVENTBRITE', 'EVENTBRITE'), ('HNET', 'HNET'), ('WEB', 'WEB')], default='WEB', max_length=100),
        ),
    ]
