# Generated by Django 3.1.6 on 2021-02-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
        ('lead', '0008_lead_eventurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='submission.submission'),
        ),
    ]
