# Generated by Django 3.1.6 on 2021-02-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='registrationDeadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
