# Generated by Django 3.1.7 on 2021-02-28 19:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0017_auto_20210228_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PARENT_TO_CHILD', 'Parent to Child'), ('EQUAL', 'Equal')], default='PARENT_TO_CHILD', max_length=100)),
                ('objectTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asObjectTags', to='tag.tag')),
                ('subjectTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asSubjectTags', to='tag.tag')),
            ],
        ),
    ]
