# Generated by Django 3.1.7 on 2021-02-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0017_auto_20210228_1926'),
        ('tagrelation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagrelation',
            old_name='type',
            new_name='relation',
        ),
        migrations.AlterField(
            model_name='tagrelation',
            name='objectTag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asObjectTags', to='tag.tag', verbose_name='Object Tag'),
        ),
        migrations.AlterField(
            model_name='tagrelation',
            name='subjectTag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asSubjectTags', to='tag.tag', verbose_name='Subject Tag'),
        ),
    ]
