# Generated by Django 3.1.6 on 2021-02-08 20:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_isanonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='helpfulness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(default='', max_length=20000),
        ),
    ]
