# Generated by Django 3.1.5 on 2021-01-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_webinar_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='recommend',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0),
        ),
    ]
