# Generated by Django 3.1.5 on 2021-01-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_auto_20210126_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='originalUrl',
            field=models.URLField(blank=True, max_length=3000),
        ),
    ]
