# Generated by Django 3.1.5 on 2021-02-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0004_auto_20210130_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='requiresRegistration',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
