# Generated by Django 3.1.6 on 2021-02-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0007_auto_20210204_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='language',
            field=models.TextField(blank=True, choices=[('cn', 'Chinese'), ('en', 'English')], default='en'),
        ),
    ]
