# Generated by Django 3.1.6 on 2021-02-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0008_webinar_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='language',
            field=models.TextField(blank=True, choices=[('CHINESE', 'Chinese'), ('ENGLISH', 'English')], default='ENGLISH'),
        ),
    ]
