# Generated by Django 3.1.6 on 2021-02-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_userprofile_savedwebinars'),
        ('webinar', '0009_auto_20210204_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='savedBy',
            field=models.ManyToManyField(blank=True, related_name='savedWebinars', to='userprofile.UserProfile'),
        ),
    ]
