# Generated by Django 3.1.6 on 2021-02-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_organization_organization_hosts'),
        ('webinar', '0010_webinar_savedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='organization',
        ),
        migrations.AddField(
            model_name='webinar',
            name='hostOrganization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostOrganization_webinar', to='organization.organization'),
        ),
    ]
