# Generated by Django 3.1.6 on 2021-02-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0012_remove_webinar_hostorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='registrationDeadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
