# Generated by Django 3.1.6 on 2021-02-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('webinar', '0013_webinar_registrationdeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinar', to='sources.source'),
        ),
    ]
