# Generated by Django 3.1.6 on 2021-02-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_source_slugname'),
        ('webinar', '0014_webinar_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars', to='sources.source'),
        ),
    ]
