# Generated by Django 3.1.6 on 2021-02-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0015_auto_20210220_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='sourcePlatformId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
