# Generated by Django 3.1.6 on 2021-02-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0016_webinar_sourceplatformid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='sourcePlatformId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
