# Generated by Django 3.1.7 on 2021-02-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0018_auto_20210222_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='lastTagged',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='lastTaggedBy',
        ),
    ]
