# Generated by Django 3.1.7 on 2021-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0021_auto_20210225_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='type',
            field=models.TextField(choices=[('WEBINAR', 'Webinars'), ('CFP', 'Call for participation'), ('READING_GROUP', 'Reading groups')], default='WEBINAR'),
        ),
    ]
