# Generated by Django 3.1.7 on 2021-02-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0022_webinar_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='startDateTimeOriginal',
            new_name='startDateTimeLocal',
        ),
        migrations.RenameField(
            model_name='webinar',
            old_name='startDateTime',
            new_name='startDateTimeUTC',
        ),
        migrations.RenameField(
            model_name='webinar',
            old_name='startDateTimeZone',
            new_name='startDateTimeZoneLocal',
        ),
    ]
