# Generated by Django 3.1.7 on 2021-02-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0023_auto_20210227_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='tagCount',
            field=models.IntegerField(default=0),
        ),
    ]
