# Generated by Django 3.1.7 on 2021-02-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0024_webinar_tagcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
