
class VIEW_TYPE_ENUM:
    MINE = 'MINE'
    TODAY = 'TODAY'
    WEEK = 'WEEK'
    MONTH = 'MONTH'

LinkTypes = [
    (VIEW_TYPE_ENUM.MINE, VIEW_TYPE_ENUM.MINE),
    (VIEW_TYPE_ENUM.TODAY, VIEW_TYPE_ENUM.TODAY),
    (VIEW_TYPE_ENUM.WEEK, VIEW_TYPE_ENUM.WEEK),
    (VIEW_TYPE_ENUM.MONTH, VIEW_TYPE_ENUM.MONTH)
]
