
class LINK_TYPE_ENUM:
    EVENT = 'EVENT'
    DETAIL = 'DETAIL'
    REGISTRATION = 'REGISTRATION'
    CONTACT = 'CONTACT'
    BROADCAST = 'BROADCAST'
    ATTACHMENT = 'ATTACHMENT'

    RECORDING = 'RECORDING'
    TRANSCRIPT = 'TRANSCRIPT'
    ORGANIZATION = 'ORGANIZATION'
    CODE = 'CODE'

LinkTypes = [
    (LINK_TYPE_ENUM.EVENT, LINK_TYPE_ENUM.EVENT),
    (LINK_TYPE_ENUM.BROADCAST, LINK_TYPE_ENUM.BROADCAST),
    (LINK_TYPE_ENUM.REGISTRATION, LINK_TYPE_ENUM.REGISTRATION),
    (LINK_TYPE_ENUM.DETAIL, LINK_TYPE_ENUM.DETAIL),
    (LINK_TYPE_ENUM.ATTACHMENT, LINK_TYPE_ENUM.ATTACHMENT),
    (LINK_TYPE_ENUM.CONTACT, LINK_TYPE_ENUM.CONTACT),
    (LINK_TYPE_ENUM.ORGANIZATION, LINK_TYPE_ENUM.ORGANIZATION),
    (LINK_TYPE_ENUM.RECORDING, LINK_TYPE_ENUM.RECORDING),
    (LINK_TYPE_ENUM.TRANSCRIPT, LINK_TYPE_ENUM.TRANSCRIPT),
    (LINK_TYPE_ENUM.CODE, LINK_TYPE_ENUM.CODE),
]
